sudo: required

dist: trusty

language: node_js

node_js:
  - '14'
install:
  - npm install
env:
  - TASK=test
matrix:
  fast_finish: true
  allow_failures:
before_script:
  - ganache-cli > /dev/null &
  - sleep 5
script:
  - npm run $TASK

notifications:
  email: false
